### ISSUE TITLE
F-11 Description

### ISSUE THREAD

**Issue by TheMisterPin** [TheMisterPin/fashion-deck#25]
# Front End Task 11 Description  
### Branch 
 ```bash 
git fetch origin
git checkout 25-f-11-description
```

## Desired Outcome 
To add a description field to the clothing, to help user identify clothing 

## Tasks 
- [x] user can add a description 
- [x] Description implemented in model 
- [x]  Description implemented in card 
- [x]  Can edit description
